package model;
// Generated Nov 8, 2016 8:51:25 AM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Astreinte generated by hbm2java
 */
public class Astreinte implements java.io.Serializable {

	private BigDecimal astreinteId;

	public Astreinte() {
	}

	public Astreinte(BigDecimal astreinteId) {
		this.astreinteId = astreinteId;
	}

	public BigDecimal getAstreinteId() {
		return this.astreinteId;
	}

	public void setAstreinteId(BigDecimal astreinteId) {
		this.astreinteId = astreinteId;
	}

}
