package model;
// Generated Nov 8, 2016 8:51:25 AM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private BigDecimal clientId;
	private String nom;
	private String prenom;

	public Client() {
	}

	public Client(BigDecimal clientId, String nom, String prenom) {
		this.clientId = clientId;
		this.nom = nom;
		this.prenom = prenom;
	}

	public BigDecimal getClientId() {
		return this.clientId;
	}

	public void setClientId(BigDecimal clientId) {
		this.clientId = clientId;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

}
