package model;
// Generated Nov 8, 2016 8:51:25 AM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.Entity;
import org.hibernate.annotations.Table;

/**
 * Cra generated by hbm2java
 */

public class Cra implements java.io.Serializable {

	private BigDecimal craId;
	private Salarie salarie;
	private Mission mission;
	private String statut;
	private Date craDate;

	public Cra() {
	}

	public Cra(BigDecimal craId, String statut) {
		this.craId = craId;
		this.statut = statut;
	}

	public Cra(BigDecimal craId, Salarie salarie, Mission mission, String statut, Date craDate) {
		this.craId = craId;
		this.salarie = salarie;
		this.mission = mission;
		this.statut = statut;
		this.craDate = craDate;
	}

	public BigDecimal getCraId() {
		return this.craId;
	}

	public void setCraId(BigDecimal craId) {
		this.craId = craId;
	}

	public Salarie getSalarie() {
		return this.salarie;
	}

	public void setSalarie(Salarie salarie) {
		this.salarie = salarie;
	}

	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Date getCraDate() {
		return this.craDate;
	}

	public void setCraDate(Date craDate) {
		this.craDate = craDate;
	}

	@Override
	public String toString() {
		return "Cra [craId=" + craId + ", salarie=" + salarie + ", mission=" 
	+ mission + ", statut=" + statut + ", craDate=" + craDate + "]";
	}
	
	
}
