package model;
// Generated Nov 8, 2016 8:51:25 AM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salarie generated by hbm2java
 */
public class Salarie implements java.io.Serializable {

	private BigDecimal salarieId;
	private String nom;
	private String prenom;
	private String poste;
	private Date dateEntree;
	private Date dateSortie;
	private Set cras = new HashSet(0);

	public Salarie() {
	}

	public Salarie(BigDecimal salarieId) {
		this.salarieId = salarieId;
	}

	public Salarie(BigDecimal salarieId, String nom, String prenom, String poste, Date dateEntree, Date dateSortie,
			Set cras) {
		this.salarieId = salarieId;
		this.nom = nom;
		this.prenom = prenom;
		this.poste = poste;
		this.dateEntree = dateEntree;
		this.dateSortie = dateSortie;
		this.cras = cras;
	}

	public BigDecimal getSalarieId() {
		return this.salarieId;
	}

	public void setSalarieId(BigDecimal salarieId) {
		this.salarieId = salarieId;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	public Date getDateEntree() {
		return this.dateEntree;
	}

	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	public Date getDateSortie() {
		return this.dateSortie;
	}

	public void setDateSortie(Date dateSortie) {
		this.dateSortie = dateSortie;
	}

	public Set getCras() {
		return this.cras;
	}

	public void setCras(Set cras) {
		this.cras = cras;
	}

}
